export const allData = [
  {
    model: "Digital Bolex D16",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS 1D C",
    free: true,
    price: null,
    user: "Jacob Jones",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Craft Camera HD",
    free: true,
    price: null,
    user: "Floyd Miles",
  },
  {
    model: "Sony UMC-S3C",
    free: true,
    price: null,
    user: "Courtney Henry",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Digital Bolex D16",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS 1D C",
    free: true,
    price: null,
    user: "Jacob Jones",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Craft Camera HD",
    free: true,
    price: null,
    user: "Floyd Miles",
  },
  {
    model: "Sony UMC-S3C",
    free: true,
    price: null,
    user: "Courtney Henry",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Digital Bolex D16",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS 1D C",
    free: true,
    price: null,
    user: "Jacob Jones",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Craft Camera HD",
    free: true,
    price: null,
    user: "Floyd Miles",
  },
  {
    model: "Sony UMC-S3C",
    free: true,
    price: null,
    user: "Courtney Henry",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Digital Bolex D16",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS 1D C",
    free: true,
    price: null,
    user: "Jacob Jones",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Craft Camera HD",
    free: true,
    price: null,
    user: "Floyd Miles",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Sony UMC-S3C",
    free: true,
    price: null,
    user: "Courtney Henry",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Digital Bolex D16",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS 1D C",
    free: true,
    price: null,
    user: "Jacob Jones",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Craft Camera HD",
    free: true,
    price: null,
    user: "Floyd Miles",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Sony UMC-S3C",
    free: true,
    price: null,
    user: "Courtney Henry",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Digital Bolex D16",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS 1D C",
    free: true,
    price: null,
    user: "Jacob Jones",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Craft Camera HD",
    free: true,
    price: null,
    user: "Floyd Miles",
  },
  {
    model: "Sony UMC-S3C",
    free: true,
    price: null,
    user: "Courtney Henry",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Digital Bolex D16",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS 1D C",
    free: true,
    price: null,
    user: "Jacob Jones",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Craft Camera HD",
    free: true,
    price: null,
    user: "Floyd Miles",
  },
  {
    model: "Sony UMC-S3C",
    free: true,
    price: null,
    user: "Courtney Henry",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Digital Bolex D16",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS 1D C",
    free: true,
    price: null,
    user: "Jacob Jones",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Craft Camera HD",
    free: true,
    price: null,
    user: "Floyd Miles",
  },
  {
    model: "Sony UMC-S3C",
    free: true,
    price: null,
    user: "Courtney Henry",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Digital Bolex D16",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS 1D C",
    free: true,
    price: null,
    user: "Jacob Jones",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Craft Camera HD",
    free: true,
    price: null,
    user: "Floyd Miles",
  },
  {
    model: "Sony UMC-S3C",
    free: true,
    price: null,
    user: "Courtney Henry",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Digital Bolex D16",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS 1D C",
    free: true,
    price: null,
    user: "Jacob Jones",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Craft Camera HD",
    free: true,
    price: null,
    user: "Floyd Miles",
  },
  {
    model: "Sony UMC-S3C",
    free: true,
    price: null,
    user: "Courtney Henry",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Craft Camera HD",
    free: true,
    price: null,
    user: "Floyd Miles",
  },
  {
    model: "Sony UMC-S3C",
    free: true,
    price: null,
    user: "Courtney Henry",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Digital Bolex D16",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS 1D C",
    free: true,
    price: null,
    user: "Jacob Jones",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Craft Camera HD",
    free: true,
    price: null,
    user: "Floyd Miles",
  },
  {
    model: "Sony UMC-S3C",
    free: true,
    price: null,
    user: "Courtney Henry",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Digital Bolex D16",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS 1D C",
    free: true,
    price: null,
    user: "Jacob Jones",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Craft Camera HD",
    free: true,
    price: null,
    user: "Floyd Miles",
  },
  {
    model: "Sony UMC-S3C",
    free: true,
    price: null,
    user: "Courtney Henry",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Digital Bolex D16",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS 1D C",
    free: true,
    price: null,
    user: "Jacob Jones",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Digital Bolex D16",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS 1D C",
    free: true,
    price: null,
    user: "Jacob Jones",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Craft Camera HD",
    free: true,
    price: null,
    user: "Floyd Miles",
  },
  {
    model: "Sony UMC-S3C",
    free: true,
    price: null,
    user: "Courtney Henry",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Digital Bolex D16",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS 1D C",
    free: true,
    price: null,
    user: "Jacob Jones",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Digital Bolex D16",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS 1D C",
    free: true,
    price: null,
    user: "Jacob Jones",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Craft Camera HD",
    free: true,
    price: null,
    user: "Floyd Miles",
  },
  {
    model: "Sony UMC-S3C",
    free: true,
    price: null,
    user: "Courtney Henry",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Digital Bolex D16",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS 1D C",
    free: true,
    price: null,
    user: "Jacob Jones",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Digital Bolex D16",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS 1D C",
    free: true,
    price: null,
    user: "Jacob Jones",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Craft Camera HD",
    free: true,
    price: null,
    user: "Floyd Miles",
  },
  {
    model: "Sony UMC-S3C",
    free: true,
    price: null,
    user: "Courtney Henry",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Digital Bolex D16",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
  {
    model: "Canon EOS 1D C",
    free: true,
    price: null,
    user: "Jacob Jones",
  },
  {
    model: "Canon EOS C700",
    free: false,
    price: "100",
    user: null,
  },
];
